language: python
python:
  - "2.7"
sudo: false
services:
  - redis-server
addons:
  postgresql: "9.3"
  packages:
    - oracle-java8-installer
before_install:
  - redis-server --version
install:
  - pip install --upgrade pip
  - pip install click natsort coverage coveralls
  - travis_retry pip install .[test]
before_script:
  # installing jira locally for testing
  - wget https://marketplace.atlassian.com/download/plugins/atlassian-plugin-sdk-tgz
  - tar zxvf atlassian-plugin-sdk-tgz
  - mv atlassian-plugin-sdk-*/ atlassian-plugin-sdk
  - export PATH="${PATH}:${PWD}/atlassian-plugin-sdk/bin"
  # making sure to start with a clean maven
  - rm -r ~/.m2/
  - atlas-version
  - tar zxvf support_files/myConfluenceMacro.tgz
  - cd myConfluenceMacro
  - atlas-run &
script:
  - git clone https://github.com/biocore/american-gut-web.git ~/build/biocore/american-gut-web
  - cd /home/travis/build/biocore/american-gut-web
  - export AG_CONFIG=`pwd`/ag_config.txt.example
  - export PYTHONPATH=/home/travis/build/biocore/american-gut-web:$PYTHONPATH
  - ./scripts/ag make test
  - export PYTHONPATH=
  - $PYTHONPATH
  - cd $TRAVIS_BUILD_DIR
  - cp $TRAVIS_BUILD_DIR/knimin/config.txt.example $TRAVIS_BUILD_DIR/knimin/config.txt
  - nosetests --with-doctest --with-coverage
  - flake8 knimin setup.py scripts
after_success:
  - coveralls
