language: python
python:
  - "2.7"
sudo: false
services:
  - redis-server
addons:
  postgresql: "9.3"
before_install:
  - redis-server --version
install:
  - pip install --upgrade pip
  - pip install mock nose>=0.10.1 pep8 flake8 coveralls
  - travis_retry pip install .
script:
  - cp ~/build/biocore/labadmin/knimin/config.txt.example ~/build/biocore/labadmin/knimin/config.txt
  - nosetests --with-doctest --with-coverage
  - git clone https://github.com/biocore/american-gut-web.git
  - ./home/travis/build/biocore/american-gut-web/scripts/ag make test
  - flake8 knimin setup.py scripts
after_success:
  - coveralls
